print("************* ")
print(" *         *  ")
print("  *  ...  *   ")
print("   *  .  *    ")
print("    *___*     ")
print("    * . *     ")
print("   *  .  *    ")
print("  *.......*   ")
print(" *.........*  ")
print("************* ")